services:
  db-dev:
    image: postgres:17-alpine
    container_name: watchdog-db-dev
    profiles: [ "dev" ]
    restart: unless-stopped
    environment:
      POSTGRES_USER: watchdog
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: watchdog_db_dev
    secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - ./Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - watchdog-network

  db-prod:
    image: postgres:17-alpine
    container_name: watchdog-db-prod
    profiles: [ "prod" ]
    restart: unless-stopped
    environment:
      POSTGRES_USER: watchdog
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: watchdog_db_prod
    secrets:
      - db_password
    ports:
      - "5433:5432"
    volumes:
      - ./Scripts/init-prod.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - watchdog-network
  
  
  app-prod:
    build: .
    container_name: watchdog-app-prod
    profiles: [ "prod" ]
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - db-prod
    networks:
      - watchdog-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  postgres_data_dev:
  postgres_data_prod:

networks:
  watchdog-network:
    driver: bridge
    